/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on 08/02/2011, 02:34:14
 */
package prime.view;

import br.com.ecftef.ViewECFTEF;
import prime.bean.Funcionario;
import prime.bean.NivelAcesso;
import prime.util.EncriptaSenha;
import prime.view.compras.CotacaoCompra;
import prime.view.compras.RequisicaoCompra;
import prime.view.compras.estoque.AjustePrecos;
import prime.view.compras.estoque.EntradaProduto;
import prime.view.financeiro.Pagamentos;
import java.beans.Beans;
import java.io.IOException;
import java.net.URL;
import java.security.spec.ECField;
import java.util.List;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Scholl
 */
public class Menu extends javax.swing.JFrame {
   // private String[] args;

    /** Creates new form Menu */
    public Menu() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

private HelpSet hs;
private HelpBroker hb;
private URL hsURL;
    
/**Este método abre o visualizador do help set e mostra
*o ID do help set
*/  
public void openHelp() {
    // Identifica a localização do arquivo .hs
    String pathToHS = "/appwithhelp/docs/appwithhelp-hs.xml";
    //Cria a URL para a localização do help set
    try {
        hsURL = getClass().getResource(pathToHS);
        hs = new HelpSet(null, hsURL);
    } catch (Exception ee) {
        System.out.println( "HelpSet " + ee.getMessage());
        System.out.println( "Help Set "+ pathToHS +" não encontrado");
        return;
    }
  
    // Cria um objeto HelpBroker para manipular o help set
    hb = hs.createHelpBroker();
    // Mostra o help set
    hb.setDisplayed(true);
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = javax.persistence.Persistence.createEntityManagerFactory("siscomjavaPU").createEntityManager();
        query = entityManager.createQuery("SELECT n FROM NivelAcesso n");
        list = query.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prime - Sistema Comercial");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jToolBar1.setBackground(new java.awt.Color(102, 204, 255));
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/users4_add444.png"))); // NOI18N
        jButton1.setToolTipText("Cadastrar um Novo Cliente");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos_add.png"))); // NOI18N
        jButton2.setToolTipText("Cadastrar um Novo Produto");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Orcamento_Red_.png"))); // NOI18N
        jButton3.setToolTipText("Realizar Orçamento");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Venda_2.png"))); // NOI18N
        jButton4.setToolTipText("Iniciar Frente de Caixa");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator5);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor_12_.png"))); // NOI18N
        jButton5.setToolTipText("Consultar / Cadastrar um Fornecedor");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadora_12.png"))); // NOI18N
        jButton6.setToolTipText("Abrir Calculadora");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);
        jToolBar1.add(jSeparator6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_3.png"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 80);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 110, 50, 30);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(680, 120, 60, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Prime_-2_.png"))); // NOI18N
        jLabel3.setToolTipText("Prime - Sistema Comercial");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 680, 410);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("© Copyright 2011 Scholl - Todos os Direitos Reservados - Design by Scholl™ Software");
        jLabel4.setToolTipText("© Copyright 2011 Scholl - Todos os Direitos Reservados - Design by Scholl™ Software");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 520, 740, 14);

        jMenu1.setLabel("Cadastro");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setMnemonic('C');
        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setMnemonic('F');
        jMenuItem2.setText("Fornecedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setMnemonic('B');
        jMenuItem3.setText("Contas Bancárias");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setMnemonic('U');
        jMenuItem4.setText("Unidades");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setMnemonic('P');
        jMenuItem5.setText("Produtos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator4);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Departamentos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setMnemonic('n');
        jMenuItem7.setText("Funcionários");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Cartões");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Plano de Contas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setMnemonic('T');
        jMenuItem10.setText("Tipo de Pgto / Rcbto");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Sair");
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setLabel("Movimento");

        jMenuItem12.setText("Contas a Pagar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Contas a Receber");
        jMenu2.add(jMenuItem13);

        jMenuItem16.setText("Vendas");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuItem29.setText("Orçamentos");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem29);

        jMenu5.setText("Controle de Estoque");

        jMenuItem14.setText("Entrada de NF");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem15.setText("Atualização de Preços");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenu2.add(jMenu5);

        jMenu6.setText("Compras");

        jMenuItem17.setText("Requisição");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem17);

        jMenuItem18.setText("Cotação");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem19.setText("Confirma Cotação");
        jMenu6.add(jMenuItem19);

        jMenuItem20.setText("Pedido");
        jMenu6.add(jMenuItem20);

        jMenu2.add(jMenu6);

        jMenu7.setText("Tesouraria e Banco");

        jMenuItem21.setText("Emissão de Cheques");
        jMenu7.add(jMenuItem21);

        jMenuItem22.setText("Conciliação de Cheques");
        jMenu7.add(jMenuItem22);

        jMenuItem23.setText("Movimento de Banco");
        jMenu7.add(jMenuItem23);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setLabel("Utilitários");

        jMenuItem24.setText("Calculadora");
        jMenu3.add(jMenuItem24);

        jMenuItem25.setText("Calendário");
        jMenu3.add(jMenuItem25);
        jMenu3.add(jSeparator2);

        jMenu8.setText("Sistema de Segurança");

        jMenuItem27.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem27.setText("Trocar Senha Corrente");
        jMenu8.add(jMenuItem27);

        jMenuItem28.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem28.setText("Definir Nível de Acesso");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem28);

        jMenu3.add(jMenu8);

        jMenuBar1.add(jMenu3);

        jMenu4.setLabel("Ajuda");

        jMenuItem30.setText("Conteúdo");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem30);

        jMenuItem26.setText("Sobre o Sistema");
        jMenu4.add(jMenuItem26);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-749)/2, (screenSize.height-600)/2, 749, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jMenuItem5ActionPerformed(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja Realmente Sair do Sistema?") == JOptionPane.YES_OPTION) {
            System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    }
      private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
          if (verificaAcesso(jMenuItem3.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Cadastro Das Contas Bancárias";
              BancoView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem3ActionPerformed

      private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
          if (verificaAcesso(jMenuItem8.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Cadastro De Cartões";
              CartaoView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }

      }//GEN-LAST:event_jMenuItem8ActionPerformed

      private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
          if (verificaAcesso(jMenuItem10.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Cadastro De Tipos de Pagamento / Recebimentos";
              TipoPgtoView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem10ActionPerformed

      private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          if (verificaAcesso(jMenuItem1.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Cadastro De Clientes";
              ClienteView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }

      }//GEN-LAST:event_jMenuItem1ActionPerformed

    private boolean verificaAcesso(String nomeMenu, String CodFuncionario) {
        query = entityManager.createNamedQuery("NivelAcesso.verifique");
        query.setParameter("codFunc", Integer.parseInt(CodFuncionario));
        query.setParameter("nomeModulo", nomeMenu);
        List<NivelAcesso> data = query.getResultList();
        if (data.size() > 0) {
            return true;
        } else {
            return false;
        }
    }

      private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          if (verificaAcesso(jMenuItem2.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Cadastro De Fornecedores";
              FornecedorView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem2ActionPerformed

      private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
          if (verificaAcesso(jMenuItem5.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Cadastro De Produtos";
              ProdutoView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem5ActionPerformed

      private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
          if (verificaAcesso(jMenuItem4.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Cadastro De Unidades";
              UnidadeView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem4ActionPerformed

      private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
          if (verificaAcesso(jMenuItem9.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Cadastro Do Plano de Contas";
              PlanoContaView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem9ActionPerformed

      private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
          if (verificaAcesso(jMenuItem6.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Cadastro De Departamentos";
              DepartamentosView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem6ActionPerformed

      private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
          if (verificaAcesso(jMenuItem7.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Cadastro De Funcionarios";
              FuncionarioView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem7ActionPerformed

      private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
          if (verificaAcesso(jMenuItem16.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Movimento - Vendas";
              MovimentoVenda.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem16ActionPerformed

      private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
          if (verificaAcesso(jMenuItem29.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Movimento - Orçamento de Venda";
              MovimentoOrcamentoVenda.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem29ActionPerformed

      private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
          if (verificaAcesso(jMenuItem18.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Movimento - Cotação de Compras";
              CotacaoCompra.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem18ActionPerformed

      private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
          if (verificaAcesso(jMenuItem17.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Movimento - Requisição de Compras";
              RequisicaoCompra.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem17ActionPerformed

      private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
          if (verificaAcesso(jMenuItem14.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Movimento - Entrada de Nfe";
              EntradaProduto.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem14ActionPerformed

      private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
          if (verificaAcesso(jMenuItem15.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Movimento - Esqtoque - Ajuste de Preços";
              AjustePrecos.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem15ActionPerformed

      private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
          if (verificaAcesso(jMenuItem12.getText(), jLabel2.getText())) {
              String args[] = new String[1];
              args[0] = "Movimento - Contas a Pagar";
              Pagamentos.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }
      }//GEN-LAST:event_jMenuItem12ActionPerformed

      private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed

          if (verificaAcesso(jMenuItem28.getText(), jLabel2.getText())) {
              String args[] = {""};
              ControleAcessoView.main(args);
          } else {
              JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
          }

      }//GEN-LAST:event_jMenuItem28ActionPerformed

      private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          jMenuItem1ActionPerformed(evt);
      }//GEN-LAST:event_jButton1ActionPerformed

      private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jMenuItem29ActionPerformed(evt);
      }//GEN-LAST:event_jButton3ActionPerformed

      private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          // TODO add your handling code here:
         // ECField.class.asSubclass(ecftef.ViewECFTEF);
         ViewECFTEF.main(null);
       // ViewECFTEF viewECFTEF =  new ViewECFTEF();

      }//GEN-LAST:event_jButton4ActionPerformed

      private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          jMenuItem2ActionPerformed(evt);
      }//GEN-LAST:event_jButton5ActionPerformed

      private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
                Runtime.getRuntime().exec("calc.exe");
            } catch (IOException e) {
                e.printStackTrace();
	}
      }//GEN-LAST:event_jButton6ActionPerformed

      private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
          openHelp();
      }//GEN-LAST:event_jMenuItem30ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
                jLabel2.setText(args[0]);
                jLabel2.setVisible(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private java.util.List list;
    private javax.persistence.Query query;
    // End of variables declaration//GEN-END:variables
}
