package prime.view.financeiro;

//import adilson.util.PrinterMatrix;
//import siscom.view.ImpressaoView;
import java.awt.EventQueue;
import java.beans.Beans;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class Pagamentos extends JPanel {

    public Pagamentos() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("siscomjavaPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Pagamento p");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        planoContaQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM PlanoConta p");
        planoContaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : planoContaQuery.getResultList();
        tipoPgtoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM TipoPgto t");
        tipoPgtoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tipoPgtoQuery.getResultList();
        bancoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM Banco b");
        bancoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : bancoQuery.getResultList();
        fornecedorQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Fornecedor f");
        fornecedorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : fornecedorQuery.getResultList();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        rowSorterToStringConverter1 = new converter.RowSorterToStringConverter();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        codPagamentoLabel = new javax.swing.JLabel();
        codPlanoContaLabel = new javax.swing.JLabel();
        codTipoPgtoLabel = new javax.swing.JLabel();
        codBancoLabel = new javax.swing.JLabel();
        codFornecedorLabel = new javax.swing.JLabel();
        numDocPagamentoLabel = new javax.swing.JLabel();
        vlrTotalPagamentoLabel = new javax.swing.JLabel();
        vlrJuroPagamentoLabel = new javax.swing.JLabel();
        vlrMultaPagamentoLabel = new javax.swing.JLabel();
        vlrDescontoPagamentoLabel = new javax.swing.JLabel();
        vlrPagoPagamentoLabel = new javax.swing.JLabel();
        numChequePagamentoLabel = new javax.swing.JLabel();
        nominalPagamentoLabel = new javax.swing.JLabel();
        emissaoPagamentoLabel = new javax.swing.JLabel();
        lancamentoPagamentoLabel = new javax.swing.JLabel();
        vencimentoPagamentoLabel = new javax.swing.JLabel();
        dataPagamentoLabel = new javax.swing.JLabel();
        dataChequePagamentoLabel = new javax.swing.JLabel();
        codPagamentoField = new javax.swing.JTextField();
        numDocPagamentoField = new javax.swing.JTextField();
        vlrTotalPagamentoField = new javax.swing.JTextField();
        vlrJuroPagamentoField = new javax.swing.JTextField();
        vlrMultaPagamentoField = new javax.swing.JTextField();
        vlrDescontoPagamentoField = new javax.swing.JTextField();
        vlrPagoPagamentoField = new javax.swing.JTextField();
        numChequePagamentoField = new javax.swing.JTextField();
        nominalPagamentoField = new javax.swing.JTextField();
        lancamentoPagamentoField = new javax.swing.JTextField();
        dataPagamentoField = new javax.swing.JTextField();
        dataChequePagamentoField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        jMenuItem1.setText("Contas Pagas");
        jMenuItem1.addActionListener(formListener);
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Contas a Pagar");
        jMenuItem2.addActionListener(formListener);
        jPopupMenu1.add(jMenuItem2);

        rowSorterToStringConverter1.setTable(masterTable);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(85, 170, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new java.awt.GridLayout(3, 1));

        jPanel5.setBackground(new java.awt.Color(85, 170, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Procurar por:");
        jPanel5.add(jLabel2, new java.awt.GridBagConstraints());

        jTextField1.setText("                                       IMPLEMENTAR O BOTÃO LOCALIZA");
        jTextField1.setPreferredSize(new java.awt.Dimension(400, 20));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${rowSorter}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(rowSorterToStringConverter1);
        bindingGroup.addBinding(binding);

        jPanel5.add(jTextField1, new java.awt.GridBagConstraints());

        jButton2.setText("Localiza");
        jPanel5.add(jButton2, new java.awt.GridBagConstraints());

        jPanel8.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(85, 170, 255));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Período:");
        jPanel6.add(jLabel3, new java.awt.GridBagConstraints());

        jTextField2.setText("01-01-2008");
        jTextField2.setPreferredSize(new java.awt.Dimension(70, 20));
        jTextField2.addActionListener(formListener);
        jPanel6.add(jTextField2, new java.awt.GridBagConstraints());

        jLabel4.setText("a:");
        jPanel6.add(jLabel4, new java.awt.GridBagConstraints());

        jTextField3.setText("31-12-2008");
        jTextField3.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel6.add(jTextField3, new java.awt.GridBagConstraints());

        jButton3.setText("Filtrar");
        jButton3.addActionListener(formListener);
        jPanel6.add(jButton3, new java.awt.GridBagConstraints());

        jPanel8.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(85, 170, 255));

        saveButton.setText("Save");
        saveButton.addActionListener(formListener);
        jPanel7.add(saveButton);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(formListener);
        jPanel7.add(refreshButton);

        newButton.setText("Incluir");
        newButton.addActionListener(formListener);
        jPanel7.add(newButton);

        deleteButton.setText("Excluir");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);
        jPanel7.add(deleteButton);

        jButton1.setText("Alterar");
        jPanel7.add(jButton1);

        jButton4.setText("Relatórios");
        jButton4.setComponentPopupMenu(jPopupMenu1);
        jPanel7.add(jButton4);

        jPanel8.add(jPanel7);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 710, 120));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTabbedPane1.setAutoscrolls(true);

        masterTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codPagamento}"));
        columnBinding.setColumnName("Cod Pagamento");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codPlanoConta}"));
        columnBinding.setColumnName("Cod Plano Conta");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codTipoPgto}"));
        columnBinding.setColumnName("Cod Tipo Pgto");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codBanco}"));
        columnBinding.setColumnName("Cod Banco");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codFornecedor}"));
        columnBinding.setColumnName("Cod Fornecedor");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numDocPagamento}"));
        columnBinding.setColumnName("Num Doc Pagamento");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vlrTotalPagamento}"));
        columnBinding.setColumnName("Vlr Total Pagamento");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vlrJuroPagamento}"));
        columnBinding.setColumnName("Vlr Juro Pagamento");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vlrMultaPagamento}"));
        columnBinding.setColumnName("Vlr Multa Pagamento");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vlrDescontoPagamento}"));
        columnBinding.setColumnName("Vlr Desconto Pagamento");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vlrPagoPagamento}"));
        columnBinding.setColumnName("Vlr Pago Pagamento");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numChequePagamento}"));
        columnBinding.setColumnName("Num Cheque Pagamento");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nominalPagamento}"));
        columnBinding.setColumnName("Nominal Pagamento");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emissaoPagamento}"));
        columnBinding.setColumnName("Emissao Pagamento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lancamentoPagamento}"));
        columnBinding.setColumnName("Lancamento Pagamento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vencimentoPagamento}"));
        columnBinding.setColumnName("Vencimento Pagamento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataPagamento}"));
        columnBinding.setColumnName("Data Pagamento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataChequePagamento}"));
        columnBinding.setColumnName("Data Cheque Pagamento");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(masterTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lista de Pagamentos num Pedíodo", jPanel1);

        codPagamentoLabel.setText("Cod Pagamento:");

        codPlanoContaLabel.setText("Plano Conta:");

        codTipoPgtoLabel.setText("Tipo Pgto:");

        codBancoLabel.setText("Banco:");

        codFornecedorLabel.setText("Fornecedor:");

        numDocPagamentoLabel.setText("Número do Documento:");

        vlrTotalPagamentoLabel.setText("Valor Total:");

        vlrJuroPagamentoLabel.setText("Valor Juro:");

        vlrMultaPagamentoLabel.setText("Valor Multa:");

        vlrDescontoPagamentoLabel.setText("Valor Desconto:");

        vlrPagoPagamentoLabel.setText("Valor Pago:");

        numChequePagamentoLabel.setText("Número do Cheque:");

        nominalPagamentoLabel.setText("Cheque Nominal a:");

        emissaoPagamentoLabel.setText("Data de Emissao:");

        lancamentoPagamentoLabel.setText("Data de Lançamento:");

        vencimentoPagamentoLabel.setText("Data de Vencimento:");

        dataPagamentoLabel.setText("Data Pagamento:");

        dataChequePagamentoLabel.setText("Data do Cheque:");

        codPagamentoField.setBackground(new java.awt.Color(255, 255, 204));
        codPagamentoField.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codPagamento}"), codPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numDocPagamento}"), numDocPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), numDocPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.vlrTotalPagamento}"), vlrTotalPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), vlrTotalPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.vlrJuroPagamento}"), vlrJuroPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), vlrJuroPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.vlrMultaPagamento}"), vlrMultaPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), vlrMultaPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.vlrDescontoPagamento}"), vlrDescontoPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), vlrDescontoPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.vlrPagoPagamento}"), vlrPagoPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), vlrPagoPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numChequePagamento}"), numChequePagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), numChequePagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nominalPagamento}"), nominalPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nominalPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.lancamentoPagamento}"), lancamentoPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), lancamentoPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataPagamento}"), dataPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), dataPagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        dataPagamentoField.addActionListener(formListener);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataChequePagamento}"), dataChequePagamentoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), dataChequePagamentoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, planoContaList, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tipoPgtoList, jComboBox2);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, bancoList, jComboBox3);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBox3.addActionListener(formListener);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, fornecedorList, jComboBox4);
        bindingGroup.addBinding(jComboBoxBinding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.emissaoPagamento}"), jFormattedTextField1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jFormattedTextField1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.vencimentoPagamento}"), jFormattedTextField2, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jFormattedTextField2, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lancamentoPagamentoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lancamentoPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataChequePagamentoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataChequePagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(nominalPagamentoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nominalPagamentoField, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(vlrPagoPagamentoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vlrPagoPagamentoField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(vlrTotalPagamentoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vlrTotalPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(vlrJuroPagamentoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vlrJuroPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vlrMultaPagamentoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vlrMultaPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vlrDescontoPagamentoLabel))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dataPagamentoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dataPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numChequePagamentoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numChequePagamentoField)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vlrDescontoPagamentoField, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codPagamentoLabel)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(codBancoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(codPlanoContaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, 0, 183, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(codTipoPgtoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(codFornecedorLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox4, 0, 451, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(numDocPagamentoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numDocPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(emissaoPagamentoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vencimentoPagamentoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codPagamentoLabel)
                    .addComponent(codPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codPlanoContaLabel)
                    .addComponent(codTipoPgtoLabel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codBancoLabel)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codFornecedorLabel)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numDocPagamentoLabel)
                    .addComponent(numDocPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vencimentoPagamentoLabel)
                    .addComponent(emissaoPagamentoLabel)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vlrTotalPagamentoLabel)
                    .addComponent(vlrTotalPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vlrJuroPagamentoLabel)
                    .addComponent(vlrJuroPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vlrMultaPagamentoLabel)
                    .addComponent(vlrMultaPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vlrDescontoPagamentoLabel)
                    .addComponent(vlrDescontoPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vlrPagoPagamentoLabel)
                    .addComponent(vlrPagoPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataPagamentoLabel)
                    .addComponent(dataPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numChequePagamentoLabel)
                    .addComponent(numChequePagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nominalPagamentoLabel)
                    .addComponent(nominalPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lancamentoPagamentoLabel)
                    .addComponent(lancamentoPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataChequePagamentoLabel)
                    .addComponent(dataChequePagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(276, 276, 276))
        );

        jTabbedPane1.addTab("Inclusão/Alteração de Pagamentos", jPanel2);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 300));

        jPanel4.setBackground(new java.awt.Color(85, 170, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Controle de Contas a Pagar / Pagas");
        jPanel4.add(jLabel1);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == jTextField2) {
                Pagamentos.this.jTextField2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton3) {
                Pagamentos.this.jButton3ActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                Pagamentos.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                Pagamentos.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                Pagamentos.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                Pagamentos.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == dataPagamentoField) {
                Pagamentos.this.dataPagamentoFieldActionPerformed(evt);
            }
            else if (evt.getSource() == jComboBox3) {
                Pagamentos.this.jComboBox3ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem1) {
                Pagamentos.this.jMenuItem1ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem2) {
                Pagamentos.this.jMenuItem2ActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<prime.bean.Pagamento> toRemove = new ArrayList<prime.bean.Pagamento>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            prime.bean.Pagamento p = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(p);
            entityManager.remove(p);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        prime.bean.Pagamento p = new prime.bean.Pagamento();
        entityManager.persist(p);
        list.add(p);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
        jTabbedPane1.setSelectedIndex(1);
        jComboBox1.requestFocus();
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<prime.bean.Pagamento> merged = new ArrayList<prime.bean.Pagamento>(list.size());
            for (prime.bean.Pagamento p : list) {
                merged.add(entityManager.merge(p));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox3ActionPerformed

private void dataPagamentoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPagamentoFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_dataPagamentoFieldActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
    
    java.util.Date ini = null;
    java.util.Date fim = null;
    
    try {
        ini = formato.parse(jTextField2.getText());
        fim = formato.parse(jTextField3.getText());
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    query = entityManager.createNamedQuery("Pagamento.findBetweenVencimento");
    query.setParameter("dataIni", ini);
    query.setParameter("dataFim", fim);
    
    java.util.Collection dadosResposta = query.getResultList();
    list.clear();
    list.addAll(dadosResposta);
}//GEN-LAST:event_jButton3ActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
    
    java.util.Date ini = null;
    java.util.Date fim = null;
    
    try {
        ini = formato.parse(jTextField2.getText());
        fim = formato.parse(jTextField3.getText());
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    query = entityManager.createNamedQuery("Pagamento.pagas");
    query.setParameter("dataIni", ini);
    query.setParameter("dataFim", fim);
    
    java.util.Collection dadosResposta = query.getResultList();
    list.clear();
    list.addAll(dadosResposta);

   /*
    PrinterMatrix printer = new PrinterMatrix();

    //Define o tamanho do papel/tela para impressão, aqui 25 linhas e 80 colunas
    printer.setOutSize(25, 80);

    printer.printCharAtCol(1, 1, 80, "=");
    printer.printTextLinCol(2, 1, "T2Ti.com - www.t2ti.com");

    printer.printCharAtCol(3, 1, 80, "=");
    printer.printTextLinCol(4, 1, "Contas Pagas - Periodo: " + jTextField2.getText() + " a " + jTextField3.getText());
    printer.printCharAtCol(5, 1, 80, "-");
    printer.printTextLinCol(6, 1, "Doc.");
    printer.printTextLinCol(6, 11, "Descricao");
    printer.printTextLinCol(6, 41, "Valor");
    printer.printTextLinCol(6, 52, "Vencimento");
    printer.printTextLinCol(6, 63, "Pagamento");
    printer.printTextLinCol(6, 74, "Cheque");
    printer.printCharAtCol(7, 1, 80, "-");

    int linha = 8;
    double total = 0.0;
    for (siscom.bean.Pagamento p : list) {

        printer.printTextLinCol(linha, 1, String.valueOf(p.getNumDocPagamento()));
        printer.printTextLinCol(linha, 11, String.valueOf(p.getNominalPagamento()));
        printer.printTextLinCol(linha, 41, String.valueOf(p.getVlrPagoPagamento()));
        printer.printTextLinCol(linha, 52, String.valueOf(formato.format(p.getVencimentoPagamento())));
        printer.printTextLinCol(linha, 63, String.valueOf(formato.format(p.getDataPagamento())));
        printer.printTextLinCol(linha, 74, String.valueOf(p.getNumChequePagamento()));
        linha++;
        total = total + p.getVlrPagoPagamento();

    }
    printer.printCharAtCol(linha, 1, 80, "-");
    printer.printTextLinCol(++linha, 1, "Total de Pagamentos >>>");
    printer.printTextLinCol(linha, 41, String.valueOf(total));
    printer.printCharAtCol(++linha, 1, 80, "-");

    printer.toFile("impressao.txt");

    String arg[] = {""};
    ImpressaoView.main(arg);

    */
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
    
    java.util.Date ini = null;
    java.util.Date fim = null;
    
    try {
        ini = formato.parse(jTextField2.getText());
        fim = formato.parse(jTextField3.getText());
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    query = entityManager.createNamedQuery("Pagamento.apagar");
    query.setParameter("dataIni", ini);
    query.setParameter("dataFim", fim);
    
    java.util.Collection dadosResposta = query.getResultList();
    list.clear();
    list.addAll(dadosResposta);

    /*
    PrinterMatrix printer = new PrinterMatrix();

    //Define o tamanho do papel/tela para impressão, aqui 25 linhas e 80 colunas
    printer.setOutSize(25, 80);

    printer.printCharAtCol(1, 1, 80, "=");
    printer.printTextLinCol(2, 1, "T2Ti.com - www.t2ti.com");

    printer.printCharAtCol(3, 1, 80, "=");
    printer.printTextLinCol(4, 1, "Contas a Pagar - Periodo: " + jTextField2.getText() + " a " + jTextField3.getText());
    printer.printCharAtCol(5, 1, 80, "-");
    printer.printTextLinCol(6, 1, "Doc.");
    printer.printTextLinCol(6, 11, "Descricao");
    printer.printTextLinCol(6, 41, "Valor");
    printer.printTextLinCol(6, 52, "Emissao");
    printer.printTextLinCol(6, 63, "Vencimento");
    printer.printCharAtCol(7, 1, 80, "-");

    int linha = 8;
    double total = 0.0;
    for (siscom.bean.Pagamento p : list) {

        printer.printTextLinCol(linha, 1, String.valueOf(p.getNumDocPagamento()));
        printer.printTextLinCol(linha, 11, String.valueOf(p.getNominalPagamento()));
        printer.printTextLinCol(linha, 41, String.valueOf(p.getVlrTotalPagamento()));
        printer.printTextLinCol(linha, 52, String.valueOf(formato.format(p.getEmissaoPagamento())));
        printer.printTextLinCol(linha, 63, String.valueOf(formato.format(p.getVencimentoPagamento())));
        linha++;
        total = total + p.getVlrTotalPagamento();

    }
    printer.printCharAtCol(linha, 1, 80, "-");
    printer.printTextLinCol(++linha, 1, "Total de Contas a Pagar >>>");
    printer.printTextLinCol(linha, 41, String.valueOf(total));
    printer.printCharAtCol(++linha, 1, 80, "-");

    printer.toFile("impressao.txt");

    String arg[] = {""};
    ImpressaoView.main(arg);
     */
}//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<prime.bean.Banco> bancoList;
    private javax.persistence.Query bancoQuery;
    private javax.swing.JLabel codBancoLabel;
    private javax.swing.JLabel codFornecedorLabel;
    private javax.swing.JTextField codPagamentoField;
    private javax.swing.JLabel codPagamentoLabel;
    private javax.swing.JLabel codPlanoContaLabel;
    private javax.swing.JLabel codTipoPgtoLabel;
    private javax.swing.JTextField dataChequePagamentoField;
    private javax.swing.JLabel dataChequePagamentoLabel;
    private javax.swing.JTextField dataPagamentoField;
    private javax.swing.JLabel dataPagamentoLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel emissaoPagamentoLabel;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<prime.bean.Fornecedor> fornecedorList;
    private javax.persistence.Query fornecedorQuery;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField lancamentoPagamentoField;
    private javax.swing.JLabel lancamentoPagamentoLabel;
    private java.util.List<prime.bean.Pagamento> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField nominalPagamentoField;
    private javax.swing.JLabel nominalPagamentoLabel;
    private javax.swing.JTextField numChequePagamentoField;
    private javax.swing.JLabel numChequePagamentoLabel;
    private javax.swing.JTextField numDocPagamentoField;
    private javax.swing.JLabel numDocPagamentoLabel;
    private java.util.List<prime.bean.PlanoConta> planoContaList;
    private javax.persistence.Query planoContaQuery;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private converter.RowSorterToStringConverter rowSorterToStringConverter1;
    private javax.swing.JButton saveButton;
    private java.util.List<prime.bean.TipoPgto> tipoPgtoList;
    private javax.persistence.Query tipoPgtoQuery;
    private javax.swing.JLabel vencimentoPagamentoLabel;
    private javax.swing.JTextField vlrDescontoPagamentoField;
    private javax.swing.JLabel vlrDescontoPagamentoLabel;
    private javax.swing.JTextField vlrJuroPagamentoField;
    private javax.swing.JLabel vlrJuroPagamentoLabel;
    private javax.swing.JTextField vlrMultaPagamentoField;
    private javax.swing.JLabel vlrMultaPagamentoLabel;
    private javax.swing.JTextField vlrPagoPagamentoField;
    private javax.swing.JLabel vlrPagoPagamentoLabel;
    private javax.swing.JTextField vlrTotalPagamentoField;
    private javax.swing.JLabel vlrTotalPagamentoLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public static void main(final String[] args) {
        EventQueue.invokeLater(new Runnable() {

            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new Pagamentos());
                //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setTitle(args[0]);
                frame.setVisible(true);
            }
        });
    }
}
